num_epochs: 500
num_timesteps: 250
num_agents: 10
num_runs: 1
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 750
  mutation_rate: 0.3
  mutation_strength: 0.5
  keep_threshold: 0.25

agent:
  type: DominAnt
  params:
    input_size: 31
    hidden_layer_size: 
    - 15
    - 8
    output_size: 3
