num_epochs: 1
num_timesteps: 1
num_agents: 20
num_runs: 1
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 50
width: 50

population:
  size: 1
  mutation_rate: 0.4
  mutation_strength: 0.5
  keep_threshold: 0.2

agent:
  number: 10
  type: DominAnt
  params:
    input_size: 13
    hidden_layer_size: 
    - 300
    - 300
    output_size: 2
