num_epochs: 20
num_timesteps: 400
num_agents: 20
num_runs: 10
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median_minvar

population:
  size: 400
  mutation_rate: 0.3
  mutation_strength: 0.2
  keep_threshold: 0.3

agent:
  type: DominAnt
  params:
    input_size: 13
    hidden_layer_size: 
    - 20
    - 25
    - 30
    - 15
    - 5
    output_size: 3
