num_epochs: 250
num_timesteps: 300
num_agents: 10
num_runs: 3
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 800
  mutation_rate: 0.1
  crossover_rate: 0.05
  crossover_flag: True
  mutation_strength: 1.0 
  keep_threshold: 0.25
  init_from_file: False
  filename: results_500.pkl

agent:
  type: DiscretAnt
  params:
    direction_bins: 7
    pheromone_bins: 5
    hidden_layer_size: 
    - 32
    - 32
