num_epochs: 5000
num_timesteps: 300
num_agents: 10
num_runs: 1
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 2000
  mutation_rate: 0.4
  crossover_rate: 0.1
  crossover_flag: True
  mutation_strength: 0.3
  keep_threshold: 0.25
  init_from_file: False
  filename: results_500.pkl

agent:
  type: DiscretAnt2
  params:
    direction_bins: 7
    hidden_layer_size: 
    - 32
    - 16
