num_epochs: 10
num_timesteps: 400
num_agents: 15
num_runs: 10
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30

population:
  size: 100
  mutation_rate: 0.5
  mutation_strength: 0.2
  keep_threshold: 0.2

agent:
  number: 10
  type: DominAnt
  params:
    input_size: 13
    hidden_layer_size: 
    - 50
    - 50
    output_size: 2