num_epochs: 10
num_timesteps: 500
num_agents: 15
num_runs: 10
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30

population:
  size: 50
  mutation_rate: 0.2
  mutation_strength: 0.4
  keep_threshold: 0.6

agent:
  type: FetchAnt
  params:
    input_size: 3
    hidden_layer_size: 
    - 100
    - 100
    output_size: 1
