num_epochs: 250
num_timesteps: 300
num_agents: 10
num_runs: 1
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 5000
  mutation_rate: 0.1
  mutation_strength: 0.5 
  keep_threshold: 0.25
  init_from_file: False
  filename: results_500.pkl

agent:
  type: IntelligAnt
  params:
    hidden_layer_size: 
    - 32
    - 16
    - 8
