num_epochs: 250
num_timesteps: 300
num_agents: 10
num_runs: 3
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 80
  mutation_rate: 0.1
  crossover_rate: 0.05
  crossover_flag: True
  mutation_strength: 1.0 
  keep_threshold: 0.25
  init_from_file: False
  filename: results_500.pkl

agent:
  type: DominAnt
  params:
    input_size: 15
    hidden_layer_size: 
    - 25
    - 15
    output_size: 3
