num_epochs: 20
num_timesteps: 500
num_agents: 15
num_runs: 10
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30

population:
  size: 500
  mutation_rate: 0.2
  mutation_strength: 0.5
  keep_threshold: 0.3

agent:
  type: DominAnt
  params:
    input_size: 13
    hidden_layer_size: 
    - 20
    - 25
    - 15
    output_size: 3
