num_epochs: 200
num_timesteps: 300
num_agents: 10
num_runs: 3
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: average

population:
  size: 800
  mutation_rate: 0.5 # this is now max mutation rate
  mutation_strength: 0.5 # deprecated, now full resamples
  keep_threshold: 0.25

agent:
  type: DominAnt
  params:
    input_size: 13
    hidden_layer_size: 
    - 20
    - 20
    - 20
    output_size: 3
