num_epochs: 100
num_timesteps: 200
num_agents: 20
num_runs: 5
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median_minvar

population:
  size: 100
  mutation_rate: 0.2
  mutation_strength: 0.5
  keep_threshold: 0.3

agent:
  type: FetchAnt
  params:
    input_size: 3
    hidden_layer_size: 
    - 8
    - 12
    - 24
    - 12
    - 8
    output_size: 1
