num_epochs: 250
num_timesteps: 300
num_agents: 10
num_runs: 3
nest_location: center
# nest_location:
#   - 0
#   - 0
height: 30
width: 30
eval: median

population:
  size: 500
  mutation_rate: 0.5
  crossover_rate: 0.2
  crossover_flag: True
  mutation_strength: 0.5
  keep_threshold: 0.25
  init_from_file: False
  filename: results_500.pkl

agent:
  type: DiscretAnt2
  params:
    direction_bins: 7
    hidden_layer_size: 
    - 32
    - 32
